### ISSUE TITLE
Generate X.509 certificate on Linux

### ISSUE THREAD

**Issue by abhatikar** [DevKitExamples/DevKitDPS#12]
Hi,

How does one Generate X.509 certificate on ubuntu linux ?
Is there a script or set of openssl commands ?

thanks

**Comment by obastemur** [comment]
clone `https://github.com/Microsoft/devkit-sdk/`

```
cd AZ3166/tools/dice_device_enrollment/src/dice_device_enrollment
make
```
so you will have it for your OS.. Beware, the name of the binary still be `dps_cert_gen_mac`.

**Comment by obastemur** [comment]
btw; you may need the https://github.com/Microsoft/devkit-sdk/pull/898 is merged first or simply use that makefile.

**Comment by ArthurMa1978** [comment]
This issue was moved to Microsoft/devkit-sdk#930
